export const GET_CLASSES_LOADING = 'GET_CLASSES_LOADING';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_ERROR = 'GET_CLASSES_ERROR';

export const DEL_CLASSES_LOADING = 'DET_CLASSES_LOADING';
export const DEL_CLASSES_SUCCESS = 'DET_CLASSES_SUCCESS';
export const DEL_CLASSES_ERROR = 'DEL_CLASSES_ERROR';
