export const GET_SUBSCRIPTIONS_PENDING = 'GET_SUBSCRIPTIONS_PENDING';
export const GET_SUBSCRIPTIONS_SUCCESS = 'GET_SUBSCRIPTIONS_SUCCESS';
export const GET_SUBSCRIPTIONS_ERROR = 'GET_SUBSCRIPTIONS_ERROR';

export const ADD_SUBSCRIPTIONS_PENDING = 'ADD_SUBSCRIPTIONS_PENDING';
export const ADD_SUBSCRIPTIONS_ERROR = 'ADD_SUBSCRIPTIONS_ERROR';
export const ADD_SUBSCRIPTIONS_SUCCESS = 'ADD_SUBSCRIPTIONS_SUCCESS';

export const PUT_SUBSCRIPTIONS_PENDING = 'PUT_SUBSCRIPTIONS_PENDING';
export const PUT_SUBSCRIPTIONS_ERROR = 'PUT_SUBSCRIPTIONS_ERROR';
export const PUT_SUBSCRIPTIONS_SUCCESS = 'PUT_SUBSCRIPTIONS_SUCCESS';

export const DEL_SUBSCRIPTIONS_PENDING = 'DEL_SUBSCRIPTIONS_PENDING';
export const DEL_SUBSCRIPTIONS_ERROR = 'DEL_SUBSCRIPTIONS_ERROR';
export const DEL_SUBSCRIPTIONS_SUCCESS = 'DEL_SUBSCRIPTIONS_SUCCESS';
