export const GET_SUBSCRIPTIONS_PENDING = 'GET_SUBSCRIPTIONS_PENDING';
export const SET_SUBSCRIPTIONS_SUCCESS = 'SET_SUBSCRIPTIONS_SUCCESS';
export const GET_SUBSCRIPTIONS_ERROR = 'GET_SUBSCRIPTIONS_ERROR';
