export const GET_TRAINERS_PENDING = 'GET_TRAINERS_PENDING';
export const GET_TRAINERS_SUCCESS = 'GET_TRAINERS_SUCCESS';
export const GET_TRAINERS_ERROR = 'GET_TRAINERS_ERROR';

export const ADD_TRAINERS_PENDING = 'ADD_TRAINERS_PENDING';
export const ADD_TRAINERS_ERROR = 'ADD_TRAINERS_ERROR';
export const ADD_TRAINERS_SUCCESS = 'ADD_TRAINERS_SUCCESS';

export const PUT_TRAINERS_PENDING = 'PUT_TRAINERS_PENDING';
export const PUT_TRAINERS_ERROR = 'PUT_TRAINERS_ERROR';
export const PUT_TRAINERS_SUCCESS = 'PUT_TRAINERS_SUCCESS';

export const DEL_TRAINERS_PENDING = 'DEL_TRAINERS_PENDING';
export const DEL_TRAINERS_ERROR = 'DEL_TRAINERS_ERROR';
export const DEL_TRAINERS_SUCCESS = 'DEL_TRAINERS_SUCCESS';
