export const GET_ADMINS_LOADING = 'GET_ADMINS_LOADING';
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS';
export const GET_ADMINS_ERROR = 'GET_ADMINS_ERROR';

export const DEL_ADMINS_LOADING = ' DEL_ADMINS_LOADING';
export const DEL_ADMINS_SUCCESS = 'DEL_ADMINS_SUCCESS';
export const DEL_ADMINS_ERROR = 'DEL_ADMINS_ERROR';

export const PUT_ADMINS_LOADING = ' PUT_ADMINS_LOADING';
export const PUT_ADMINS_SUCCESS = 'PUT_ADMINS_SUCCESS';
export const PUT_ADMINS_ERROR = 'PUT_ADMINS_ERROR';

export const POST_ADMINS_LOADING = ' POST_ADMINS_LOADING';
export const POST_ADMINS_SUCCESS = 'POST_ADMINS_SUCCESS';
export const POST_ADMINS_ERROR = 'POST_ADMINS_ERROR';
